version: '3.8'

services:
  spring-boot-app:
    image: spring-boot-github-action-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
